#!/bin/sh

total_mem=$(/usr/bin/free -m | /usr/bin/awk '$1 == "Mem:" { print $2 }')

while(true); do
  current_mem=$(/usr/bin/free -m | /usr/bin/awk '$1 == "-/+" { print $3 }')
  current_mem_percentage=$(echo ${current_mem} ${total_mem} | /usr/bin/awk '{print $1/$2 * 100.0}')
  echo "${current_mem_percentage}%(${current_mem}/${total_mem} MB)"
  sleep 3
done
