#!/bin/bash

total_mem=$(/usr/bin/free -m | /usr/bin/awk '$1 == "Mem:" { print $2 }')
target=3.3.9
current_version=$(/usr/bin/free -V | /usr/bin/awk '{print $4}')

vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    #local i ver1=($target) ver2=($current_version)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

vercomp $current_version $target
case $? in
  0) op='=';;
  1) op='>';;
  2) op='<';;
esac
#echo "free version: $current_version $op $target"
if [[ $op != '>' ]]
then
  isLessUbuntu1404='yes'
#      echo "FAIL: Expected '$3', Actual '$op', Arg1 '$1', Arg2 '$2'"
fi

while(true); do
  if [[ $isLessUbuntu1404 == 'yes' ]]
  then
    # ubuntu 14.04
    current_mem=$(/usr/bin/free -m | /usr/bin/awk '$1 == "-/+" { print $3 }')
  else
  # ubuntu 16.04
    current_mem=$(/usr/bin/free -m | /usr/bin/awk '$1 == "Mem:" { print $3 }')
  fi
  current_mem_percentage=$(echo ${current_mem} ${total_mem} | /usr/bin/awk '{print $1/$2 * 100.0}')
  echo "${current_mem_percentage}%(${current_mem}/${total_mem} MB)"
  sleep 3
done
